matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
      - .github/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  - '**/*.mdx'
  default_encoding: utf-8
